# Generated by Django 6.0.4 on 2026-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label for this hero variant', max_length=120)),
                ('badge_text', models.CharField(blank=True, help_text='Small pill shown above the headline', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(default='Browse the shop', max_length=40)),
                ('cta_primary_url', models.CharField(default='/shop/', max_length=200)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=40)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional right-side image', upload_to='hero/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one hero should be active at a time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hero section',
                'verbose_name_plural': 'hero sections',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Short tagline shown under the category title', max_length=300),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_product_count',
            field=models.PositiveIntegerField(default=4, help_text='How many products to show in the home section'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured_on_home',
            field=models.BooleanField(default=False, help_text='Show this category as its own section on the home page'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in the Featured section on the home page'),
        ),
    ]
