# Generated by Django 6.0.4 on 2026-04-17 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_hero_category_description_category_featured_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='PyCommerce', max_length=100)),
                ('store_tagline', models.CharField(blank=True, default='A modern Django storefront with a clean, simple checkout.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Optional — replaces the "P" badge in the navbar', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('contact_email', models.EmailField(blank=True, default='hello@pycommerce.example', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_address_line', models.CharField(blank=True, default='PyCommerce HQ', max_length=200)),
                ('contact_address', models.CharField(blank=True, default='ul. Marshal Tito 123, 7000 Bitola, North Macedonia', max_length=300)),
                ('contact_hours', models.CharField(blank=True, default='Mon–Fri, 9:00–17:00', max_length=120)),
                ('map_latitude', models.DecimalField(decimal_places=6, default=Decimal('41.029700'), max_digits=9)),
                ('map_longitude', models.DecimalField(decimal_places=6, default=Decimal('21.329700'), max_digits=9)),
                ('map_zoom', models.PositiveSmallIntegerField(default=15)),
                ('map_popup_title', models.CharField(default='PyCommerce HQ', max_length=120)),
                ('map_popup_subtitle', models.CharField(blank=True, default='ul. Marshal Tito 123, Bitola', max_length=200)),
                ('about_badge', models.CharField(default='Our story', max_length=60)),
                ('about_headline', models.CharField(default='Commerce, done properly.', max_length=200)),
                ('about_lead', models.TextField(blank=True, default='PyCommerce is a modern online shop built with Django, combining a clean admin for store owners with a fast, simple checkout for customers.')),
                ('about_body', models.TextField(blank=True, default='Our mission is straightforward: curate great products, price them fairly, and make browsing effortless.')),
                ('about_stat_1_value', models.CharField(blank=True, default='10k+', max_length=20)),
                ('about_stat_1_label', models.CharField(blank=True, default='Happy customers', max_length=60)),
                ('about_stat_2_value', models.CharField(blank=True, default='500+', max_length=20)),
                ('about_stat_2_label', models.CharField(blank=True, default='Products curated', max_length=60)),
                ('about_stat_3_value', models.CharField(blank=True, default='4.9', max_length=20)),
                ('about_stat_3_label', models.CharField(blank=True, default='Avg. review score', max_length=60)),
                ('about_stat_4_value', models.CharField(blank=True, default='24h', max_length=20)),
                ('about_stat_4_label', models.CharField(blank=True, default='Typical ship time', max_length=60)),
                ('show_featured_products', models.BooleanField(default=True)),
                ('show_on_sale_section', models.BooleanField(default=True)),
                ('show_category_sections', models.BooleanField(default=True)),
                ('show_newsletter_section', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
