# Generated by Django 6.0.4 on 2026-04-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_is_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, help_text='Alt text for screen readers', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports line breaks. Rendered as plain text.')),
                ('scope', models.CharField(choices=[('global', 'Global — show on every product'), ('category', 'Category — show on all products in a category'), ('product', 'Product — show on a single product')], default='global', max_length=20)),
                ('is_collapsible', models.BooleanField(default=True, help_text='If off, the section always shows expanded with no toggle.')),
                ('default_open', models.BooleanField(default=False, help_text='When collapsible, controls whether the section starts expanded.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Required when scope is Category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sections', to='store.category')),
                ('product', models.ForeignKey(blank=True, help_text='Required when scope is Product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
