# Generated by Django 6.0.4 on 2026-04-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage_productsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Groups options into one selector. e.g. "Size", "Grind".', max_length=100)),
                ('value', models.CharField(help_text='e.g. "Small", "Whole bean".', max_length=100)),
                ('price_delta', models.DecimalField(blank=True, decimal_places=2, help_text='Added to the base price when selected. Leave empty for no change.', max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the group.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='store.product')),
            ],
            options={
                'ordering': ['group_name', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'group_name', 'value'), name='uniq_product_variant_option')],
            },
        ),
    ]
