# Generated by Django 6.0.4 on 2026-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productvariantoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4 recommended). Takes priority over the URL below.', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL (e.g. https://www.youtube.com/embed/…). Used when no file is uploaded.'),
        ),
    ]
