# Generated by Django 6.0.4 on 2026-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_about_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the order categories (and their products) appear in the shop. Lower numbers appear first.'),
        ),
    ]
